<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AddUsuario.aspx.cs" Inherits="MVPG52.AddUsuario" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron card-panel teal white ">

        <nav class="" data-target="red" style="top: auto; z-index: auto">
            <div class="nav-wrapper #311b92 deep-purple darken-1">
                <div class="container center-align">
                    <h3 class="">Agrear Usuarios</h3>
                    <ul id="nav-mobile2" class="right hide-on-med-and-down">
                    </ul>
                </div>
            </div>
        </nav>
        <br />
        <div class="row">
            <ul class="collapsible " data-collapsible="accordion" style="font-size: x-large">
                <li>
                    <div class="collapsible-header"><i class="material-icons">person_pin</i>Descropción.</div>
                    <div class="collapsible-body  jumbotron  card-panel teal white">
                        <p style="font-size: medium">Se podran agrear personal medico al sistema  </p>

                    </div>
                </li>
            </ul>
        </div>

        <ul class="nav nav-tabs">
            <li class="active">
                <a data-toggle="tab" href="#Consulta" class="card-panel #2196f3 blue white-text">Consulta/Baja</a>
            </li>
            <li>
                <a data-toggle="tab" href="#Alta" class="card-panel #ff6f00 amber darken-4 white-text">Alta</a>
            </li>
            <li>
                <asp:HyperLink ID="HyperLinkMedico" runat="server"  data-toggle="tab" href="#Modificacion" class="card-panel #d81b60 pink darken-1 white-text">Modificacion</asp:HyperLink>
            </li>
        </ul>

        <!--Contenido de tabs-->
        <div class="tab-content">
            <!----Pestañana 1-->
            <div id="Consulta" class="tab-pane fade in active">
                <nav class="" data-target="red" style="top: auto; z-index: auto">
                    <div class="nav-wrapper #2196f3 blue white-text">
                        <div class="container center-align">
                            <h3 class=""></h3>
                            <ul id="nav-mobile2" class="right hide-on-med-and-down">
                            </ul>
                        </div>
                    </div>
                </nav>
                <asp:GridView ID="GridViewEmpleados" runat="server" Font-Size="Small" CssClass="highlight  responsive-table table table-striped table table-hover " AutoGenerateDeleteButton="False" AllowSorting="False"></asp:GridView>
            </div>
            <!----Pestañana 2-->
            <div id="Alta" class="tab-pane fade">
                <nav class="" data-target="red" style="top: auto; z-index: auto">
                    <div class="nav-wrapper #ff6f00 amber darken-4 white-text">
                        <div class="container center-align">
                            <h3 class=""></h3>
                            <ul id="nav-mobile2" class="right hide-on-med-and-down">
                            </ul>
                        </div>
                    </div>
                </nav>
               
               
                <%-- Datos generales --%>
                <div style="color: cornflowerblue">
                    <h3>Datos Generales</h3>
                </div>
                <div class="row">
                    <div class="input-field  col-md-4">
                        <asp:TextBox ID="Nombre" runat="server" Font-Size="Medium"></asp:TextBox>
                        <div>
                           
                        </div>
                        <label for="Nombre">Nombre</label>
                    </div>
                    <div class="input-field  col-md-4 ">
                        <asp:TextBox ID="Temperatura" runat="server" Font-Size="Medium"></asp:TextBox>
                        <div class=" ">
                            <asp:RegularExpressionValidator ID="RegularExpressionValidator6" runat="server" ErrorMessage="Solo números" ForeColor="Red" BackColor="Yellow" ControlToValidate="Temperatura" ValidationExpression="^\d+(?:[\.\,]\d+)?$"></asp:RegularExpressionValidator>
                        </div>
                        <label for="Talla">Temperatura</label>
                    </div>
                    <div class="input-field  col-md-4">
                        <asp:TextBox ID="Peso" runat="server" Font-Size="Medium"></asp:TextBox>
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" ErrorMessage="Solo números" ForeColor="Red" BackColor="Yellow" ControlToValidate="Peso" ValidationExpression="\d*\.?\d*" Font-Size="Medium"></asp:RegularExpressionValidator>
                        <label for="Peso">Peso(Kg)</label>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col-md-4">
                        <asp:TextBox ID="RtimoCardiaco" runat="server" Font-Size="Medium"></asp:TextBox>
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator5" runat="server" ErrorMessage="Solo números" ForeColor="Red" BackColor="Yellow" ControlToValidate="RtimoCardiaco" ValidationExpression="\d*\.?\d*" Font-Size="Medium"></asp:RegularExpressionValidator>
                        <label for="Peso">Ritmo Cardiaco</label>
                    </div>
                    <div class="input-field col-md-2">
                        <asp:TextBox ID="Presion" runat="server" Font-Size="Medium"></asp:TextBox>
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator3" runat="server" ErrorMessage="Solo números" ForeColor="Red" BackColor="Yellow" ControlToValidate="Presion" ValidationExpression="^[0-9]*" Font-Size="Medium"></asp:RegularExpressionValidator>
                        <label for="Presion">Presión Arterial(mm)</label>
                    </div>
                    <div class="input-field col-md-2">
                        <asp:TextBox ID="Presion1" runat="server" Font-Size="Medium"></asp:TextBox>
                        <asp:RegularExpressionValidator ID="RegularExpressionValidator4" runat="server" ErrorMessage="Solo números" ForeColor="Red" BackColor="Yellow" ControlToValidate="Presion1" ValidationExpression="^[0-9]*" Font-Size="Medium"></asp:RegularExpressionValidator>
                        <label for="Presion">Presión Arterial(Hg)</label>
                    </div>
                </div>
               
                <div class="row">
                    <div class="input-field  col-md-4">
                        <asp:TextBox ID="DiasReposo" runat="server" Font-Size="Medium"></asp:TextBox>
                        <div>
                            <asp:RegularExpressionValidator ID="RegularExpressionValidator7" runat="server" ErrorMessage="Solo números, sin puntos" ForeColor="Red" BackColor="Yellow" ControlToValidate="Talla" ValidationExpression="^[0-9]*"></asp:RegularExpressionValidator>
                        </div>
                        <label for="Talla">Días</label>
                    </div>

                </div>
            
                <%--  --%>
               
            </div>
            <!----Pestañana 3-->
            <div id="Modificacion" class="tab-pane fade">
                <nav class="" data-target="red" style="top: auto; z-index: auto">
                    <div class="nav-wrapper #d81b60 pink darken-1 white-text">
                        <div class="container center-align">
                            <h3 class=""></h3>
                            <ul id="nav-mobile2" class="right hide-on-med-and-down">
                            </ul>
                        </div>
                    </div>
                </nav>
                <div style="color: cornflowerblue">
                    <h3>Datos del alumno</h3>
                </div>
                <%-- Datos del alumno --%>

               

            </div>
          
           
        </div>
    </div>
</asp:Content>
